### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by SamanAtashi** [Loosescrew022/Week1-project#2]

**Comment by SamanAtashi** [comment]
I like how you manage to organize the basic skeleton of HTML.
I suggest organize navbar with more div's like right ,center , left.

**Comment by danmainah** [comment]
Good code,I love the code flow easy to follow ,you forgot to include the tab

**Comment by Coolczycki** [comment]
Added the tab as suggested.
Added styling to navbar.

Thank you for your suggestions.
